version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: fastapi-backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPEN_WEBUI_API_URL: ${OPEN_WEBUI_API_URL}
      OPEN_WEBUI_API_KEY: ${OPEN_WEBUI_API_KEY}
      TEXTBELT_API_KEY: ${TEXTBELT_API_KEY}
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
